
services:
  mysql:
    image: mysql:8.0
    container_name: autodiagnostico-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: autodiagnostico
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: autodiagnostico-backend
    restart: unless-stopped
    ports:
      - "7777:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/autodiagnostico?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    volumes:
      - ./backend/src/main/resources/scraper-output:/app/scraper-output
      - ./backend/src/main/resources/logos:/app/logos
      - ./backend/src/main/resources/models:/app/models
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: autodiagnostico-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
