spring.application.name=Autodiagnostico
server.port=8081

# Data Source Configuration (MySQL)
spring.datasource.url=jdbc:mysql://mysql:3306/autodiagnostico?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# CORS Configuration
spring.web.cors.allowed-origins=http://localhost:80



# Debugging
logging.level.root=INFO
logging.level.org.springframework=DEBUG
logging.level.your.package=TRACE

# Show SQL if using JPA
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

